### PR TITLE
feat(slack): Support set username and icon from template in slack

### PR DESCRIPTION
**Pull request by ayatk**
When multiple users set triggers and templates for one slack service in monorepos, etc., there was an issue where the icon and username could not be changed. Therefore, I made it possible to set a custom username and icon in the template used for Slack notifications.

If the username and icon are already set on the service side and the username and icon are also set on the template, the template will take priority.

And there were no tests for Slack notifications, so I added them.

### CODE REVIEW

**Review by reggie-k — COMMENTED** [review]
I have tested locally and found that in some use cases the notification is sent once with the username and icon, and once without them, meaning with the default ones, I tried that with "on-sync-succeeded" trigger.

**Comment by ayatk** [comment]
@reggie-k Thank you for your review!

I'm sorry, but I don't really understand the situation. Is it okay to understand that in the case of the "on-sync-succeeded" trigger, two notifications are sent: one with the username and icon set, and one without?

**Comment by reggie-k** [comment]
> @reggie-k Thank you for your review!
> 
> I'm sorry, but I don't really understand the situation. Is it okay to understand that in the case of the "on-sync-succeeded" trigger, two notifications are sent: one with the username and icon set, and one without?

Yeah, exactly

**Comment by ayatk** [comment]
I looked into it, but I couldn't reproduce the situation you described...
When I tested it using `go run examples/certmanager/cli/main.go template notify`, I was able to set the icon and username without any problems, so I think the problem is probably somewhere else (such as the config) that is not related to this PR.

> I have tested locally and found that in some use cases the notification is sent once with the username and icon, and once without them, meaning with the default ones, I tried that with "on-sync-succeeded" trigger.

I would like to confirm, does this problem occur in the revision before this PR? For example, if the same problem does not occur when the `username` and `icon` fields are set in `service.slack`, I will know that the code I wrote is causing the problem.

**Comment by reggie-k** [comment]
Not sure I understand what to confirm? The problem is that, while the icon and username are set in the config like described in the docs of this PR, in the 2 slack notifications produced upon manually syncing the app from the UI, only one is actually with the username and icon configured, and the other one does not have the username and the icon.

**Comment by reggie-k** [comment]
I reproduced it upon running locally `make run` and then syncing the app from the UI. 
This is how the sync notification look like in slack:
Screenshot 2024-09-30 at 16 46 30


You can see that there are 3 messages sent to slack, only one of them is with the icon and the username, and two look like default icon and username.

**Review by reggie-k — APPROVED** [review]
Sorry!
This was a problem with my local config.
LGTM

**Comment by ayatk** [comment]
@reggie-k @pasha-codefresh 
Thank you for review!

**Pull request merged**
