### PR TITLE
feat: Update aws-sdk-go-v2 for EKS Pod Identities

### PR DESCRIPTION
**Pull request by ROunofF**
Update aws-sdk-go-v2 to support EKS Pod Identities

Will update the indirect in https://github.com/argoproj/argo-cd/pull/16641

### CODE REVIEW

**Comment by csantanapr** [comment]
Was testing this patch and sqs notifications are failing
```
time="2024-01-21T04:50:06Z" level=error msg="Got an error getting the queue URL: not found, ResolveEndpointV2"
time="2024-01-21T04:50:06Z" level=error msg="Failed to notify recipient {awssqs ArgoCDNotifications} defined in resource argocd/workload-dev: not found, ResolveEndpointV2 using the configuration in namespace argocd" resource=argocd/workload-dev
```
I tried with and without specifying account/region/endpointUrl

It looks like there is a problem with the sdk version, we might need to update more components to latest 
I found this issue https://github.com/aws/aws-sdk-go-v2/issues/2370

**Comment by csantanapr** [comment]
@ROunofF I sent you a PR to fix the sqs issue, I tested and it works
https://github.com/ROunofF/notifications-engine/pull/1

**Comment by csantanapr** [comment]
@todaywasawesome @crenshaw-dev would you be kind to review this PR? 🙏

**Review by crenshaw-dev — APPROVED** [review]

**Comment by csantanapr** [comment]
Thank you @crenshaw-dev 🎉

**Pull request merged**
