### PR TITLE
Add GitHub Deployment integration

### LINKED ISSUE #98: Support for GitHub deployments
It’d be great to add additional functionality to the GitHub integration so that it supports creating/updating deployments using the deployments API.

https://docs.github.com/en/rest/deployments/deployments

### PR DESCRIPTION
**Pull request by jaredtbates**
Currently, this creates the Deployment as well as the DeploymentStatus in one go. This is because I couldn't figure out how to preserve the deployment ID across different events. If anyone has any ideas of how to do that, please let me know!

Fixes #98

### CODE REVIEW

**Comment by jaredtbates** [comment]
Do you want me to try to add tests for the service logic? The previous integration didn't have tests for that, and I'm not sure I'm familiar enough with Go to mock the GitHub services. Open to learning if it's needed though!

**Comment by jaredtbates** [comment]
I've tested this in a custom build of Argo and it works great with deployments!

**Comment by jaredtbates** [comment]
@nan-yu, what is the best way to get a review on this? I just saw you were tagged on another PR a few weeks ago and figured maybe this PR didn't notify anyone, so thought I'd give it a try. Apologies if you are not the right person to ping. Thank you!

**Comment by nan-yu** [comment]
@jaredtbates I am not an owner of this repo. I was tagged because my colleague and I would like to contribute as well.

It seems @pasha-codefresh and @alexmt recently reviewed and approved PRs. I would suggest tagging them for review.

**Comment by jaredtbates** [comment]
Thank you, @pasha-codefresh and @alexmt, if you get any time, could you take a look at your convenience? No rush, but would appreciate your input. We're running a custom build of Argo internally in the meantime.

**Comment by pasha-codefresh** [comment]
@jaredtbates PR looks good to me, could you please resolve conflicts?

**Comment by jaredtbates** [comment]
@pasha-codefresh thanks for looking at this! I just merged in the latest changes and resolved conflicts. Let me know if anything else needs done!

**Comment by pasha-codefresh** [comment]
Thank you!

**Pull request merged**
