### PR TITLE
docs: use real cm name instead of placeholder

### PR DESCRIPTION
**Pull request by dosmanak**
Related to https://github.com/argoproj/argo-cd/pull/17002

### CODE REVIEW

**Review by gdsoumya — APPROVED** [review]
LGTM

**Comment by blakepettersson** [comment]
@dosmanak you'll need to signoff your commit(s)

**Review by todaywasawesome — APPROVED** [review]
approved pending commit signoffs...

**Comment by gdsoumya** [comment]
@dosmanak merged this PR, hopefully now the argocd PR would be fixed.

**Comment by kzap** [comment]
These docs also get merged into `argo-rollouts` ....

**Pull request merged**
