### PR TITLE
Add support for multiple to email addresses in single recepient

### PR DESCRIPTION
**Pull request by gokulav137**
This adds support for comma separated email addresses to add capability to send emails with multiple email addresses as recipients.

Current implementation only allows an email to be sent to one email address at a time.
This enhancement will add support to send a email with multiple to addresses.

Eg:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: another
  annotations:
    notifications.argoproj.io/subscriptions: |
      - trigger: [on-cert-ready]
        destinations:
          - service: email
            recipients: ["email1@gmail.com,email2@gmail.com", email2@gmail.com]
spec:
  secretName: something
  issuerRef:
    name: letsencrypt-staging
  emailAddresses:
    - email1@gmail.com
```
Tested locally

Resolves: #222

### CODE REVIEW

**Comment by gokulav137** [comment]
Hi @pasha-codefresh, Could you please review this PR

**Comment by pasha-codefresh** [comment]
LGTM, what do you think about trim whitespaces ? i think a lot of users will user user1@gmail.com, user2@gmail.com and so

@gokulav137

**Comment by gokulav137** [comment]
> LGTM, what do you think about trim whitespaces ? i think a lot of users will user user1@gmail.com, user2@gmail.com and so on
> 
> 
> 
> @gokulav137 

That seems like a good addition. Will add that logic.

**Comment by gokulav137** [comment]
Hi @pasha-codefresh, added the trim. Hope this looks good.

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
Great job, thank you

**Pull request merged**
