### PR TITLE
Add CardsV2 Support to Google Chat

### LINKED ISSUE #158: Upgrade Google chat integration to Cards V2
Currently the Google Chat integration uses the [Cards V1](https://developers.google.com/chat/api/reference/rest/v1/cards-v1) format but is deprecated in favor for [Cards V2](https://developers.google.com/chat/api/reference/rest/v1/cards).

### PR DESCRIPTION
**Pull request by tpaulus**
This change adds support for Googles _new_ CardSV2 format which replaces the now deprecated V1 format. The Google Generated shapes are now used for Message parsing to ensure complete coverage and accuracy between the docs and what the Google APIs expect.

Added unit tests and update docs to reflect these changes.

Fixes #158

### CODE REVIEW

**Comment by pims** [comment]
@zachaller @mayzhang2000 would one of you be able to dedicate some time to reviewing this PR in the near future?
The desired end goal is to have this functionality available in the next realease of argo-rollouts.

We’ve been running with this patch for a while now and it's working very well.

Thank you 🙏

**Comment by pasha-codefresh** [comment]
@tpaulus could you please fix conflicts, also WDYT about support of two versions? ( v1 and v2 ).

**Comment by tpaulus** [comment]
PR has been rebased against master.

As for how V1 and V2 support works, there is a new Struct called `cardsV2` which exposes the new shapes, while the original `cards` interface remains the same. The change is backwards compatible, while still enabling the new card items, which cannot be translated to the new interface because there is little to no overlap between V1 and V2 modules (thanks Google).

**Comment by pasha-codefresh** [comment]
Yeah, but once people update notification engine in their argocd instances, their notifications will stop work until they migrate to new templating and so on

**Comment by tpaulus** [comment]
I'm not sure I follow, the V1 interface is still supported by the integration and nothing changed with the shape of the V1 integration other than using the Google Protobuffs for the notification, which are the same as what was previously there. The `TestCardMessage_GoogleChat` Unit Test shows that this still works, as the input remains unchanged.

**Comment by pasha-codefresh** [comment]
Get it, @tpaulus , i will review it tomorrow and will back to you

**Comment by pasha-codefresh** [comment]
Great job @tpaulus , thanks

**Pull request merged**
