### PR TITLE
chore: Upgrade sprig from v2.22.0 to v3.2.3

### PR DESCRIPTION
**Pull request by umi0410**
The newer version of [sprig](https://github.com/Masterminds/sprig) which is a package for templating enables users to use much more helpful templating functions.
For example, `get` or `dig` template function from the newer version can replace current complex `if...else...` condition expressions in notification-engine configurations!
For that, This PR upgrades sprig version from the very older version to a newer version([v3.2.3](https://github.com/Masterminds/sprig/tree/v3.2.3)).

### CODE REVIEW

**Comment by lacarvalho91** [comment]
i need this too as the current version used doesn't have the `fromJson` function.

@pasha-codefresh would it be possible to have this merged?

**Comment by lacarvalho91** [comment]
@pasha-codefresh @alexmt is there someone else this can be assigned to for reviews? i appreciate its rarely easy to find time for this sort of thing! :slightly_smiling_face:

**Comment by umi0410** [comment]
@lacarvalho91 Thanks for keeping an eye on this :)

**Review by alexmt — APPROVED** [review]
Sorry, the review took forever. No objections to upgrade sprig! LGTM

**Pull request merged**
