### PR TITLE
docs: Add documentation for RocketChat

### PR DESCRIPTION
**Pull request by alexmt**
PR is based on https://github.com/argoproj/notifications-engine/pull/6 and resolved reviewer all reviewer's suggestions except adding screenshot.

### CODE REVIEW

**Comment by alexmt** [comment]
@ryota-sakamoto can you take a look please?

**Review by ryota-sakamoto — CHANGES_REQUESTED** [review]
@alexmt 
Thank you for supporting, it looks almost good, but I have only one request, please add to `Service Types`.
https://github.com/argoproj/notifications-engine/blob/aa774e755de808339b9790c995ce8fd14120f003/docs/services/overview.md#L39-L49

**Comment by alexmt** [comment]
Updated service types. Thank you!

**Comment by sergeyshevch** [comment]
@alexmt @ryota-sakamoto Sorry. I was realy busy and had no time to fix review requests in previous pull request. Thank you for finishing it

**Pull request merged**
