### PR TITLE
Allow user to skip verification on self-signed certs

### PR DESCRIPTION
**Pull request by jocelynthode**
The generic webhook is hardcoded to not skip insecure. I would like to be able to specify this as a webhook option.

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
@jocelynthode could you please mention such an option in the documentation?

**Comment by jocelynthode** [comment]
@pasha-codefresh : Oh wow, I had completely forgotten about this PR! Glad it's getting some attention :) 

I have added documentation for the generic webhook as well as added the option to be used in the tests.

Let me know if I need to do something else

**Comment by pasha-codefresh** [comment]
Please not forget update it in argocd

**Comment by jocelynthode** [comment]
What do you mean? should I do something more to have this feature land in argocd?

**Comment by pasha-codefresh** [comment]
This package used in argocd as dependency, you beed also update it here

**Pull request merged**
