### PR TITLE
github: reuse existing deployment when sending new notification

### PR DESCRIPTION
**Pull request by MrFreezeex**
Try to list existing deployment with the same sha/environment/ref and reuse it if found. This allows ArgoCD notification to update the same deployment with multiple deployment status instead of creating a new one on each deployment notification.

### CODE REVIEW

**Comment by MrFreezeex** [comment]
Hi @jaredtbates I saw that you mentioned in your Initial pull request that you didn't find a way to preserve deployment id, what do you think about this patch?

**Comment by pasha-codefresh** [comment]
@MrFreezeex could you please resolve conflicts and make sure that you have added tests?

**Comment by MrFreezeex** [comment]
> @MrFreezeex could you please resolve conflicts and make sure that you have added tests?

Hi @pasha-codefresh! I just rebased the code but I can't realistically add test unfortunately. This whole function is not tested and AFAIK there are no tests on any `Send` method anywhere. The tests are up until the actual `Send` is done but then it's always untested code afaik,

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
LGTM, thank you

**Pull request merged**
