### PR TITLE
feat: add deliveryPolicy option for slack notifications

### PR DESCRIPTION
**Pull request by dlh**
The delivery policy controls how slack messages are sent. The available modes are `Post` (default), `PostAndUpdate`, and `Update`.

---

Note: I used `runtime.FuncForPC` in several tests, which is used in other tests. This works fine in go 1.16, however in [1.17 this technique no longer works](https://golang.org/doc/go1.17#compiler):
> Functions containing closures can now be inlined

https://pkg.go.dev/runtime#FuncForPC:
> If pc represents multiple functions because of inlining, it returns the *Func describing the innermost function, but with an entry of the outermost function. 

If inlining is disabled (`go test -gcflags=-l ./...`) the tests pass with go 1.17.

### CODE REVIEW

**Comment by dlh** [comment]
Ping 👋 . Can I please get a review for these changes?

**Comment by dlh** [comment]
Ping 👋,  can I please get a review for these changes? @alexmt @ryota-sakamoto (or another maintainer)

I think the option to have a top-level slack message with the current sync status is useful.

slack-message-updated

**Comment by alexmt** [comment]
@pasha-codefresh can you please help with review ?

**Comment by pasha-codefresh** [comment]
Sure, @dlh i am checking

**Comment by pasha-codefresh** [comment]
Great job with refactoring @dlh . i just have small comments

**Comment by pasha-codefresh** [comment]
@dlh could you help me understand an issue. I have changed the config to `deliveryPolicy: PostAndUpdate` and I can see that it is just Post and not doing an actual update. It is because `ts != "" && (policy == Update || policy == PostAndUpdate)` ts is empty for me. Could you point me what I am doing wrong?

**Review by pasha-codefresh — APPROVED** [review]
LGTM, great job with refactoring

**Comment by dlh** [comment]
After merging, is it possible to have these changes included in the imminent argo-cd 2.3 release?

**Comment by james-callahan** [comment]
One weird thing with `PostAndUpdate` is that you lose the first notification that started a thread.

**Pull request merged**
